name: Deploy

on:
  push:
    branches: [ master ]

env:
  VERCEL_ORG: itering

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install vercel
        run: npm i -g vercel

      - name: Deploy rust docs
        run: |
          cd rust-docs
          vercel --token ${{ secrets.VERCEL_TOKEN }} --scope ${VERCEL_ORG} link --confirm
          vercel --token ${{ secrets.VERCEL_TOKEN }} --scope ${VERCEL_ORG} deploy --prod

      - name: Deploy forward camp
        run: |
          cd forward-camp
          vercel --token ${{ secrets.VERCEL_TOKEN }} --scope ${VERCEL_ORG} link --confirm
          vercel --token ${{ secrets.VERCEL_TOKEN }} --scope ${VERCEL_ORG} deploy --prod

